spring.application.name=vn-play-analytics

spring.datasource.url=${VN_DB_URL:jdbc:mysql://localhost:3308/vn_analytics}
spring.datasource.username=${VN_DB_USERNAME:vn_app}
spring.datasource.password=${VN_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false